# Generated by Django 2.2.10 on 2020-07-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200721_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interact',
            name='upvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
