# Generated by Django 2.2.10 on 2020-07-21 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_auto_20200721_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='total_vote',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='request',
            name='votes_total',
            field=models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
