# Generated by Django 2.2.10 on 2020-07-21 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200721_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interact',
            name='reque',
        ),
        migrations.AlterField(
            model_name='interact',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
