# Generated by Django 2.2.10 on 2020-07-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200721_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='interact',
            name='reque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Request'),
        ),
    ]
